global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "zra_rules.yml"

scrape_configs:
  - job_name: 'zra-app'
    static_configs:
      - targets: ['zra-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093


